### ISSUE TITLE
Integrate validation of new CODEX metadata against JSON schema

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/ingest-validation-tests#9]
@VasylVaskivskyi created a JSON schema for a new standardized version of the CODEX metadata, [here](https://github.com/hubmapconsortium/codex-common-acquisition-metadata/blob/master/metadata_standard/1.0/experiment_schema.json). Integrate into this repository so this validation is performed for new CODEX datasets.

**Comment by mccalluc** [comment]
I've contributed #11. Blocked by differences of opinion about the value and role of CI, but I don't think any more work is in my court. Unassigning myself.

**Comment by jswelling** [comment]
Closed by https://github.com/hubmapconsortium/ingest-validation-tests/pull/11
